export default {
  INVALID_EMAIL: "INVALID_EMAIL",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  MISSING_PASSWORD: "MISSING_PASSWORD",
  SHORT_PASSWORD: "SHORT_PASSWORD",
  TOO_LONG_PASSWORD: "TOO_LONG_PASSWORD",
};
